import 'package:flutter/material.dart';
import 'package:gymflow_core/gymflow_core.dart';

/// The member's training and meal programs, as written by their coach or
/// generated by the AI module.
class ProgramsScreen extends StatefulWidget {
  const ProgramsScreen({super.key});

  @override
  State<ProgramsScreen> createState() => _ProgramsScreenState();
}

class _ProgramsScreenState extends State<ProgramsScreen> {
  List<WorkoutPlan> _workouts = const [];
  List<NutritionPlan> _meals = const [];
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    setState(() => _loading = true);

    try {
      final response = await SessionScope.of(context).api.get('/me/programs');
      final json = (response as Map).cast<String, dynamic>();

      setState(() {
        _workouts = ((json['workout_plans'] as List?) ?? const [])
            .cast<Map>()
            .map((row) => WorkoutPlan.fromJson(row.cast<String, dynamic>()))
            .toList();
        _meals = ((json['nutrition_plans'] as List?) ?? const [])
            .cast<Map>()
            .map((row) => NutritionPlan.fromJson(row.cast<String, dynamic>()))
            .toList();
      });
    } on ApiException catch (error) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(error.message)));
      }
    } finally {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final t = TranslationsScope.of(context);

    if (_loading && _workouts.isEmpty && _meals.isEmpty) {
      return const Center(child: CircularProgressIndicator(color: AppTheme.brand));
    }

    return RefreshIndicator(
      onRefresh: _load,
      color: AppTheme.brand,
      backgroundColor: AppTheme.ink800,
      child: ListView(
        padding: const EdgeInsets.fromLTRB(16, 12, 16, 110),
        children: [
          Text(
            t.t('members.programs', 'Programs'),
            style: Theme.of(context).textTheme.headlineSmall,
          ),
          const SizedBox(height: 16),

          if (_workouts.isEmpty && _meals.isEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 60),
              child: Center(
                child: Text(
                  t.t('members.no_programs', 'Your coach has not written a program yet.'),
                  textAlign: TextAlign.center,
                  style: Theme.of(context).textTheme.bodySmall,
                ),
              ),
            ),

          for (final plan in _workouts) _WorkoutCard(plan: plan),
          for (final plan in _meals) _NutritionCard(plan: plan),
        ],
      ),
    );
  }
}

class _WorkoutCard extends StatelessWidget {
  const _WorkoutCard({required this.plan});

  final WorkoutPlan plan;

  @override
  Widget build(BuildContext context) {
    final t = TranslationsScope.of(context);

    return GlassCard(
      margin: const EdgeInsets.only(bottom: 14),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Expanded(
                child: Text(plan.title, style: Theme.of(context).textTheme.titleMedium),
              ),
              if (plan.generatedByAi)
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: AppTheme.brand.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(999),
                  ),
                  child: const Text('✨ AI', style: TextStyle(fontSize: 11, color: AppTheme.brand)),
                ),
            ],
          ),
          const SizedBox(height: 10),

          // Each day is a panel the member can open at the rack.
          for (final day in plan.days)
            Theme(
              data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
              child: ExpansionTile(
                tilePadding: EdgeInsets.zero,
                childrenPadding: const EdgeInsets.only(bottom: 8),
                iconColor: AppTheme.brand,
                collapsedIconColor: AppTheme.ink400,
                title: Text(
                  '${t.t('members.day', 'Day')} ${day.dayNumber}'
                  '${day.title == null ? '' : ' · ${day.title}'}',
                  style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w600),
                ),
                children: [
                  for (final exercise in day.exercises)
                    Padding(
                      padding: const EdgeInsets.symmetric(vertical: 5),
                      child: Row(
                        children: [
                          Expanded(
                            child: Text(
                              exercise.name,
                              style: Theme.of(context).textTheme.bodySmall,
                            ),
                          ),
                          Text(
                            exercise.volume,
                            style: const TextStyle(
                              color: AppTheme.brand,
                              fontWeight: FontWeight.w700,
                              fontSize: 13,
                            ),
                          ),
                        ],
                      ),
                    ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}

class _NutritionCard extends StatelessWidget {
  const _NutritionCard({required this.plan});

  final NutritionPlan plan;

  @override
  Widget build(BuildContext context) {
    final t = TranslationsScope.of(context);

    return GlassSection(
      margin: const EdgeInsets.only(bottom: 14),
      title: plan.title,
      subtitle: plan.dailyCalories == null
          ? null
          : '${plan.dailyCalories} kcal ${t.t('members.per_day', 'per day')}',
      child: Column(
        children: [
          for (final meal in plan.meals)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 6),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  SizedBox(
                    width: 52,
                    child: Text(
                      meal.time ?? '',
                      style: Theme.of(context).textTheme.labelSmall,
                    ),
                  ),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          '${t.t('ai.meal_${meal.type}', meal.type)} · ${meal.title}',
                          style: const TextStyle(
                            color: Colors.white,
                            fontWeight: FontWeight.w600,
                            fontSize: 13,
                          ),
                        ),
                        if (meal.description != null)
                          Text(
                            meal.description!,
                            style: Theme.of(context).textTheme.bodySmall,
                          ),
                      ],
                    ),
                  ),
                  if (meal.calories != null)
                    Text(
                      '${meal.calories}',
                      style: Theme.of(context).textTheme.labelSmall,
                    ),
                ],
              ),
            ),
        ],
      ),
    );
  }
}
